project       : SSLAD-2D                   # project file that contains parameters
compound_coef : 0                           # coefficients of efficientdet or model size
num_workers   : 2                           # num_workers of dataloader
batch_size    : 10                          # number of images per batch among all devices
head_only     : False                       # whether finetunes only the regressor and the classifier,useful in early stage convergence or small/easy dataset
lr            : 0.0001                      # leaning rate
optim         : adamw                       # select optimizer for training, suggest using admaw until the very final stage then switch to sgd
num_epochs    : 5
val_interval  : 1                           # Number of epoches between validation phases
save_interval : 500                         # Number of steps between saving
es_min_delta  : 0.0                         # Early stoppins parameter: minimum change loss to qualify as an improvement
es_patience   : 0                           # Early stopping parameter: number of epochs with no improvement after which training will be stopped. Set to 0 to disable this technique.
data_path     : D:/Workspace/Data/datasets/ # the root folder of dataset
log_path      : logs
load_weights  : weights/efficientdet-d0.pth      # whether to load weights from a checkpoint, set None to initialize, set \'last\' to load last checkpoint')
saved_path    : runs                        # root path to save the training results
debug         : False                       # whether visualize the predicted boxes of training,'the output images will be in test/')

# weights and bias
wandb           : True                  # save results to wandb, set False if you don't want to log to wandb  
wandb_project   : test                  # wandb project name
wandb_run_name  : efficientdet_d1       # wandb run name
