# reference https://docs.ultralytics.com/modes/train/#train-settings

# training configuration
path    : /mnt/d/Workspace/personal/detnets/datasets/ # dataset root dir
train   : SSLAD-2D-YOLO/images/train  # train images (relative to 'path') 118287 images
val     : SSLAD-2D-YOLO/images/val  # val images (relative to 'path') 5000 images
test    : test-dev2017.txt 
device  : cpu
names   : 
  0 : Pedestrian
  1 : Cyclist
  2 : Car
  3 : Truck
  4 : Tram
  5 : Tricycle
# saving results to wandb and local dir
wandb     : False            # save results to weights and bias
project   : SSLAD-2D     # results will be saved to runs/project/run_name
run_name  : yolov8n

train_cfg :
  weight     : yolov8n.pt     # pretrained model choices - yolov8n.pt yolov8s.pt yolov8m.pt yolov8l.pt yolov8x.pt
  workers    : 8
  epochs     : 100
  batch_size : 64
  patience   : 100         # Number of epochs to wait without improvement in validation metrics before early stopping the training. Helps prevent overfitting by stopping training when performance plateaus.
  imgsz      : 640         # Target image size for training. All images are resized to this dimension before being fed into the model. Affects model accuracy and computational complexity.
  save       : True        # Enables saving of training checkpoints and final model weights. Useful for resuming training or model deployment.
  save_period : -1         # Frequency of saving model checkpoints, specified in epochs. A value of -1 disables this feature. Useful for saving interim models during long training sessions.
  cache      : False       # Enables caching of dataset images in memory (True/ram), on disk (disk), or disables it (False). Improves training speed by reducing disk I/O at the cost of increased memory usage.
  optimizer  : 'auto'      # Choice of optimizer for training. Options include SGD, Adam, AdamW, NAdam, RAdam, RMSProp etc., or auto for automatic selection based on model configuration. Affects convergence speed and stability.
  verbose    : False       # Enables verbose output during training, providing detailed logs and progress updates. Useful for debugging and closely monitoring the training process.
  seed       : 0           # Sets the random seed for training, ensuring reproducibility of results across runs with the same configurations.
  cos_lr     : False       # Utilizes a cosine learning rate scheduler, adjusting the learning rate following a cosine curve over epochs. Helps in managing learning rate for better convergence.
  close_mosaic : 10        # Disables mosaic data augmentation in the last N epochs to stabilize training before completion. Setting to 0 disables this feature.
  profile    : False       # Enables profiling of ONNX and TensorRT speeds during training, useful for optimizing model deployment.
  lr0        : 0.01        # Initial learning rate (i.e. SGD=1E-2, Adam=1E-3) . Adjusting this value is crucial for the optimization process, influencing how rapidly model weights are updated.
  lrf        : 0.01        # Final learning rate as a fraction of the initial rate = (lr0 * lrf), used in conjunction with schedulers to adjust the learning rate over time.
  momentum   : 0.937       # Momentum factor for SGD or beta1 for Adam optimizers, influencing the incorporation of past gradients in the current update.
  plots      : False       # Generates and saves plots of training and validation metrics, as well as prediction examples, providing visual insights into model performance and learning progression.

val_cfg :
  weight      : yolov8n.pt  # your trained weight or sth
  conf        : 0.5
  iou         : 0.5
  imgsz       : 640
  half        : False
  max_det     : 300
  save_json   : False     # If True, saves the results to a JSON file for further analysis or integration with other tools.

# inference configuration
inference : 
  weight      : yolov8n.pt # your trained weight or sth
  source      : datasets/demo.jpg       # image or video to run inference
  conf        : 0.5
  iou         : 0.5
  imgsz       : 640
  half        : False
  max_det     : 300
  visualize   : False
  show        : False
  save        : True